# Verkefni 5
### Pétur Daníel Ámundason
### pda3@hi.is

In [15]:
import numpy as np
A = np.array([[0,1,0,0,1],[1,0,1,0,0],[0,0,1,1,1],[1,0,0,0,0],[0,0,0,1,0]])
print(A)

def generate_edges(graph):
    edges = []
    for node in graph:
        for neighbour in graph[node]:
            edges.append((node, neighbour))

    return edges

print(generate_edges(A))


[[0 1 0 0 1]
 [1 0 1 0 0]
 [0 0 1 1 1]
 [1 0 0 0 0]
 [0 0 0 1 0]]
[(array([0, 1, 0, 0, 1]), array([0, 1, 0, 0, 1])), (array([0, 1, 0, 0, 1]), array([1, 0, 1, 0, 0])), (array([0, 1, 0, 0, 1]), array([0, 1, 0, 0, 1])), (array([0, 1, 0, 0, 1]), array([0, 1, 0, 0, 1])), (array([0, 1, 0, 0, 1]), array([1, 0, 1, 0, 0])), (array([1, 0, 1, 0, 0]), array([1, 0, 1, 0, 0])), (array([1, 0, 1, 0, 0]), array([0, 1, 0, 0, 1])), (array([1, 0, 1, 0, 0]), array([1, 0, 1, 0, 0])), (array([1, 0, 1, 0, 0]), array([0, 1, 0, 0, 1])), (array([1, 0, 1, 0, 0]), array([0, 1, 0, 0, 1])), (array([0, 0, 1, 1, 1]), array([0, 1, 0, 0, 1])), (array([0, 0, 1, 1, 1]), array([0, 1, 0, 0, 1])), (array([0, 0, 1, 1, 1]), array([1, 0, 1, 0, 0])), (array([0, 0, 1, 1, 1]), array([1, 0, 1, 0, 0])), (array([0, 0, 1, 1, 1]), array([1, 0, 1, 0, 0])), (array([1, 0, 0, 0, 0]), array([1, 0, 1, 0, 0])), (array([1, 0, 0, 0, 0]), array([0, 1, 0, 0, 1])), (array([1, 0, 0, 0, 0]), array([0, 1, 0, 0, 1])), (array([1, 0, 0, 0, 0]), array([0

[[1 0 1 1 0]
 [0 1 1 1 2]
 [1 0 1 2 1]
 [0 1 0 0 1]
 [1 0 0 0 0]]
